set_property SRC_FILE_INFO {cfile:f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0_in_context.xdc rfile:../../../Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0_in_context.xdc id:1 order:EARLY scoped_inst:Mars_AX3_i/CPU/mdm_0} [current_design]
set_property SRC_FILE_INFO {cfile:f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_dlmb_bram_if_cntlr_0/Mars_AX3_dlmb_bram_if_cntlr_0/Mars_AX3_dlmb_bram_if_cntlr_0_in_context.xdc rfile:../../../Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_dlmb_bram_if_cntlr_0/Mars_AX3_dlmb_bram_if_cntlr_0/Mars_AX3_dlmb_bram_if_cntlr_0_in_context.xdc id:2 order:EARLY scoped_inst:Mars_AX3_i/CPU/microblaze_local_memory/dlmb_bram_if_cntlr} [current_design]
set_property SRC_FILE_INFO {cfile:f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_ilmb_bram_if_cntlr_0/Mars_AX3_ilmb_bram_if_cntlr_0/Mars_AX3_ilmb_bram_if_cntlr_0_in_context.xdc rfile:../../../Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_ilmb_bram_if_cntlr_0/Mars_AX3_ilmb_bram_if_cntlr_0/Mars_AX3_ilmb_bram_if_cntlr_0_in_context.xdc id:3 order:EARLY scoped_inst:Mars_AX3_i/CPU/microblaze_local_memory/ilmb_bram_if_cntlr} [current_design]
set_property SRC_FILE_INFO {cfile:f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0_in_context.xdc rfile:../../../Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0_in_context.xdc id:4 order:EARLY scoped_inst:Mars_AX3_i/Memory/SDRAM} [current_design]
set_property SRC_FILE_INFO {cfile:f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0_in_context.xdc rfile:../../../Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0_in_context.xdc id:5 order:EARLY scoped_inst:Mars_AX3_i/Ethernet/axi_ethernet} [current_design]
set_property SRC_FILE_INFO {cfile:f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0_in_context.xdc rfile:../../../Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0_in_context.xdc id:6 order:EARLY scoped_inst:Mars_AX3_i/Ethernet/clk_wiz} [current_design]
set_property SRC_FILE_INFO {cfile:F:/GitHub/Mars_AX3_PM3_Reference_Design/src/Mars_AX3_PM3.tcl rfile:../../../../../src/Mars_AX3_PM3.tcl id:7 unmanaged:yes} [current_design]
current_instance Mars_AX3_i/CPU/mdm_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 [get_ports {}]
current_instance
current_instance Mars_AX3_i/CPU/microblaze_local_memory/dlmb_bram_if_cntlr
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance Mars_AX3_i/CPU/microblaze_local_memory/ilmb_bram_if_cntlr
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance Mars_AX3_i/Memory/SDRAM
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
current_instance Mars_AX3_i/Ethernet/axi_ethernet
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:5 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports gtx_clk] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports gtx_clk] -edges {1 2 3} -edge_shift {2.000 2.000 2.000} [get_ports {}]
current_instance
current_instance Mars_AX3_i/Ethernet/clk_wiz
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:7 line:33 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA02_N}]
set_property src_info {type:XDC file:7 line:34 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA02_P}]
set_property src_info {type:XDC file:7 line:35 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA03_N}]
set_property src_info {type:XDC file:7 line:36 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA03_P}]
set_property src_info {type:XDC file:7 line:37 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA04_N}]
set_property src_info {type:XDC file:7 line:38 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA04_P}]
set_property src_info {type:XDC file:7 line:39 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA05_N}]
set_property src_info {type:XDC file:7 line:40 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA05_P}]
set_property src_info {type:XDC file:7 line:41 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA06_N}]
set_property src_info {type:XDC file:7 line:42 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA06_P}]
set_property src_info {type:XDC file:7 line:43 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA07_N}]
set_property src_info {type:XDC file:7 line:44 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA07_P}]
set_property src_info {type:XDC file:7 line:45 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA08_N}]
set_property src_info {type:XDC file:7 line:46 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA08_P}]
set_property src_info {type:XDC file:7 line:47 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA09_N}]
set_property src_info {type:XDC file:7 line:48 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA09_P}]
set_property src_info {type:XDC file:7 line:49 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA10_N}]
set_property src_info {type:XDC file:7 line:50 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA10_P}]
set_property src_info {type:XDC file:7 line:51 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA11_N}]
set_property src_info {type:XDC file:7 line:52 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA11_P}]
set_property src_info {type:XDC file:7 line:53 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA12_N}]
set_property src_info {type:XDC file:7 line:54 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA12_P}]
set_property src_info {type:XDC file:7 line:55 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA13_N}]
set_property src_info {type:XDC file:7 line:56 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA13_P}]
set_property src_info {type:XDC file:7 line:57 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA14_N}]
set_property src_info {type:XDC file:7 line:58 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA14_P}]
set_property src_info {type:XDC file:7 line:59 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA15_N}]
set_property src_info {type:XDC file:7 line:60 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA15_P}]
set_property src_info {type:XDC file:7 line:61 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA16_N}]
set_property src_info {type:XDC file:7 line:62 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA16_P}]
set_property src_info {type:XDC file:7 line:63 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA19_N}]
set_property src_info {type:XDC file:7 line:64 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA19_P}]
set_property src_info {type:XDC file:7 line:65 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA20_N}]
set_property src_info {type:XDC file:7 line:66 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D8    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA20_P}]
set_property src_info {type:XDC file:7 line:67 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA21_N}]
set_property src_info {type:XDC file:7 line:68 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA21_P}]
set_property src_info {type:XDC file:7 line:69 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA22_N}]
set_property src_info {type:XDC file:7 line:70 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E7    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA22_P}]
set_property src_info {type:XDC file:7 line:71 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA23_N}]
set_property src_info {type:XDC file:7 line:72 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA23_P}]
set_property src_info {type:XDC file:7 line:73 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA24_N}]
set_property src_info {type:XDC file:7 line:74 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA24_P}]
set_property src_info {type:XDC file:7 line:75 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA25_N}]
set_property src_info {type:XDC file:7 line:76 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA25_P}]
set_property src_info {type:XDC file:7 line:77 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA26_N}]
set_property src_info {type:XDC file:7 line:78 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA26_P}]
set_property src_info {type:XDC file:7 line:79 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA27_N}]
set_property src_info {type:XDC file:7 line:80 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA27_P}]
set_property src_info {type:XDC file:7 line:81 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA28_N}]
set_property src_info {type:XDC file:7 line:82 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA28_P}]
set_property src_info {type:XDC file:7 line:83 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA29_N}]
set_property src_info {type:XDC file:7 line:84 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA29_P}]
set_property src_info {type:XDC file:7 line:85 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA30_N}]
set_property src_info {type:XDC file:7 line:86 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA30_P}]
set_property src_info {type:XDC file:7 line:87 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA31_N}]
set_property src_info {type:XDC file:7 line:88 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C6    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA31_P}]
set_property src_info {type:XDC file:7 line:89 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA32_N}]
set_property src_info {type:XDC file:7 line:90 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B1    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA32_P}]
set_property src_info {type:XDC file:7 line:91 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA33_N}]
set_property src_info {type:XDC file:7 line:92 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA33_P}]
set_property src_info {type:XDC file:7 line:93 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA00_CC_N}]
set_property src_info {type:XDC file:7 line:94 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N5    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA00_CC_P}]
set_property src_info {type:XDC file:7 line:95 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA01_CC_N}]
set_property src_info {type:XDC file:7 line:96 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA01_CC_P}]
set_property src_info {type:XDC file:7 line:97 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F3    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA17_CC_N}]
set_property src_info {type:XDC file:7 line:98 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F4    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA17_CC_P}]
set_property src_info {type:XDC file:7 line:99 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA18_CC_N}]
set_property src_info {type:XDC file:7 line:100 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E2    IOSTANDARD LVCMOS18  } [get_ports {FMC_LA18_CC_P}]
set_property src_info {type:XDC file:7 line:101 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T4    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK0_M2C_N}]
set_property src_info {type:XDC file:7 line:102 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T5    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK0_M2C_P}]
set_property src_info {type:XDC file:7 line:103 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D3    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK1_M2C_N}]
set_property src_info {type:XDC file:7 line:104 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3    IOSTANDARD LVCMOS18  } [get_ports {FMC_CLK1_M2C_P}]
set_property src_info {type:XDC file:7 line:107 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V2    IOSTANDARD LVCMOS18  } [get_ports {FX3_A1}]
set_property src_info {type:XDC file:7 line:108 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V7    IOSTANDARD LVCMOS18  } [get_ports {FX3_CLK}]
set_property src_info {type:XDC file:7 line:109 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U11   IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ4}]
set_property src_info {type:XDC file:7 line:110 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13   IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ5}]
set_property src_info {type:XDC file:7 line:111 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T13   IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ6_SDCD_N}]
set_property src_info {type:XDC file:7 line:112 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11   IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ7}]
set_property src_info {type:XDC file:7 line:113 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V9    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ8}]
set_property src_info {type:XDC file:7 line:114 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U6    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ9}]
set_property src_info {type:XDC file:7 line:115 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U9    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ10}]
set_property src_info {type:XDC file:7 line:116 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V5    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ11}]
set_property src_info {type:XDC file:7 line:117 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T3    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ12}]
set_property src_info {type:XDC file:7 line:118 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R3    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ13}]
set_property src_info {type:XDC file:7 line:119 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V4    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ14}]
set_property src_info {type:XDC file:7 line:120 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U7    IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ15}]
set_property src_info {type:XDC file:7 line:121 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V6    IOSTANDARD LVCMOS18  } [get_ports {FX3_FLAGA}]
set_property src_info {type:XDC file:7 line:122 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U2    IOSTANDARD LVCMOS18  } [get_ports {FX3_FLAGB_BTN_N}]
set_property src_info {type:XDC file:7 line:127 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17   IOSTANDARD LVCMOS18  } [get_ports {I2C_INT_N}]
set_property src_info {type:XDC file:7 line:128 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17   IOSTANDARD LVCMOS18  } [get_ports {I2C_SCL}]
set_property src_info {type:XDC file:7 line:129 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18   IOSTANDARD LVCMOS18  } [get_ports {I2C_SDA}]
set_property src_info {type:XDC file:7 line:136 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M16   IOSTANDARD LVCMOS18  } [get_ports {LED0_N}]
set_property src_info {type:XDC file:7 line:137 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17   IOSTANDARD LVCMOS18  } [get_ports {LED1_N}]
set_property src_info {type:XDC file:7 line:138 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18   IOSTANDARD LVCMOS18  } [get_ports {LED2_N}]
set_property src_info {type:XDC file:7 line:139 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18   IOSTANDARD LVCMOS18  } [get_ports {LED3_N}]
set_property src_info {type:XDC file:7 line:143 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16   IOSTANDARD LVCMOS18  } [get_ports {CLK50_R}]
set_property src_info {type:XDC file:7 line:144 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17   IOSTANDARD LVCMOS18  } [get_ports {Clk50_DDR}]
set_property src_info {type:XDC file:7 line:147 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D17   IOSTANDARD SSTL15    } [get_ports {DDR3_BA[0]}]
set_property src_info {type:XDC file:7 line:148 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14   IOSTANDARD SSTL15    } [get_ports {DDR3_BA[1]}]
set_property src_info {type:XDC file:7 line:149 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15   IOSTANDARD SSTL15    } [get_ports {DDR3_BA[2]}]
set_property src_info {type:XDC file:7 line:150 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A18   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[0]}]
set_property src_info {type:XDC file:7 line:151 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E16   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[1]}]
set_property src_info {type:XDC file:7 line:152 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A15   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[2]}]
set_property src_info {type:XDC file:7 line:153 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E15   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[3]}]
set_property src_info {type:XDC file:7 line:154 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B18   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[4]}]
set_property src_info {type:XDC file:7 line:155 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B17   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[5]}]
set_property src_info {type:XDC file:7 line:156 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A16   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[6]}]
set_property src_info {type:XDC file:7 line:157 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B16   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[7]}]
set_property src_info {type:XDC file:7 line:158 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B14   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[8]}]
set_property src_info {type:XDC file:7 line:159 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C14   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[9]}]
set_property src_info {type:XDC file:7 line:160 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17   IOSTANDARD SSTL15    } [get_ports {DDR3_A[0]}]
set_property src_info {type:XDC file:7 line:161 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14   IOSTANDARD SSTL15    } [get_ports {DDR3_A[1]}]
set_property src_info {type:XDC file:7 line:162 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18   IOSTANDARD SSTL15    } [get_ports {DDR3_A[2]}]
set_property src_info {type:XDC file:7 line:163 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D18   IOSTANDARD SSTL15    } [get_ports {DDR3_A[3]}]
set_property src_info {type:XDC file:7 line:164 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13   IOSTANDARD SSTL15    } [get_ports {DDR3_A[4]}]
set_property src_info {type:XDC file:7 line:165 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E17   IOSTANDARD SSTL15    } [get_ports {DDR3_A[5]}]
set_property src_info {type:XDC file:7 line:166 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13   IOSTANDARD SSTL15    } [get_ports {DDR3_A[6]}]
set_property src_info {type:XDC file:7 line:167 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN E18   IOSTANDARD SSTL15    } [get_ports {DDR3_A[7]}]
set_property src_info {type:XDC file:7 line:168 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17   IOSTANDARD SSTL15    } [get_ports {DDR3_A[8]}]
set_property src_info {type:XDC file:7 line:169 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F18   IOSTANDARD SSTL15    } [get_ports {DDR3_A[9]}]
set_property src_info {type:XDC file:7 line:170 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14   IOSTANDARD SSTL15    } [get_ports {DDR3_CKE[0]}]
set_property src_info {type:XDC file:7 line:171 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C17   IOSTANDARD DIFF_SSTL15} [get_ports {DDR3_CLK_N[0]}]
set_property src_info {type:XDC file:7 line:172 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C16   IOSTANDARD DIFF_SSTL15} [get_ports {DDR3_CLK_P[0]}]
set_property src_info {type:XDC file:7 line:173 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B13   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[10]}]
set_property src_info {type:XDC file:7 line:174 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D14   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[11]}]
set_property src_info {type:XDC file:7 line:175 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F13   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[12]}]
set_property src_info {type:XDC file:7 line:176 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A11   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[13]}]
set_property src_info {type:XDC file:7 line:177 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F14   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[14]}]
set_property src_info {type:XDC file:7 line:178 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B11   IOSTANDARD SSTL15    } [get_ports {DDR3_DQ[15]}]
set_property src_info {type:XDC file:7 line:179 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16   IOSTANDARD SSTL15    } [get_ports {DDR3_ODT[0]}]
set_property src_info {type:XDC file:7 line:180 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D9    IOSTANDARD LVCMOS18  } [get_ports {DDR3_VSEL}]
set_property src_info {type:XDC file:7 line:181 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15   IOSTANDARD SSTL15    } [get_ports {DDR3_WE_N}]
set_property src_info {type:XDC file:7 line:182 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G16   IOSTANDARD SSTL15    } [get_ports {DDR3_A[10]}]
set_property src_info {type:XDC file:7 line:183 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G18   IOSTANDARD SSTL15    } [get_ports {DDR3_A[11]}]
set_property src_info {type:XDC file:7 line:184 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16   IOSTANDARD SSTL15    } [get_ports {DDR3_A[12]}]
set_property src_info {type:XDC file:7 line:185 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G17   IOSTANDARD SSTL15    } [get_ports {DDR3_A[13]}]
set_property src_info {type:XDC file:7 line:186 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F16   IOSTANDARD SSTL15    } [get_ports {DDR3_CAS_N}]
set_property src_info {type:XDC file:7 line:187 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D15   IOSTANDARD SSTL15    } [get_ports {DDR3_DM[0]}]
set_property src_info {type:XDC file:7 line:188 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN D12   IOSTANDARD SSTL15    } [get_ports {DDR3_DM[1]}]
set_property src_info {type:XDC file:7 line:189 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN F15   IOSTANDARD SSTL15    } [get_ports {DDR3_RAS_N}]
set_property src_info {type:XDC file:7 line:190 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A14   IOSTANDARD DIFF_SSTL15} [get_ports {DDR3_DQS_N[0]}]
set_property src_info {type:XDC file:7 line:191 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12   IOSTANDARD DIFF_SSTL15} [get_ports {DDR3_DQS_N[1]}]
set_property src_info {type:XDC file:7 line:192 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN A13   IOSTANDARD DIFF_SSTL15} [get_ports {DDR3_DQS_P[0]}]
set_property src_info {type:XDC file:7 line:193 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12   IOSTANDARD DIFF_SSTL15} [get_ports {DDR3_DQS_P[1]}]
set_property src_info {type:XDC file:7 line:194 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN G13   IOSTANDARD SSTL15    } [get_ports {DDR3_RESET_N}]
set_property src_info {type:XDC file:7 line:203 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14   IOSTANDARD LVCMOS18  } [get_ports {ETH_MDC}]
set_property src_info {type:XDC file:7 line:204 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16   IOSTANDARD LVCMOS18  } [get_ports {ETH_RXD[0]}]
set_property src_info {type:XDC file:7 line:205 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17   IOSTANDARD LVCMOS18  } [get_ports {ETH_RXD[1]}]
set_property src_info {type:XDC file:7 line:206 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15   IOSTANDARD LVCMOS18  } [get_ports {ETH_RXD[2]}]
set_property src_info {type:XDC file:7 line:207 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16   IOSTANDARD LVCMOS18  } [get_ports {ETH_RXD[3]}]
set_property src_info {type:XDC file:7 line:208 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14   IOSTANDARD LVCMOS18  } [get_ports {ETH_RXC}]
set_property src_info {type:XDC file:7 line:209 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18   IOSTANDARD LVCMOS18  } [get_ports {ETH_TXD[0]}]
set_property src_info {type:XDC file:7 line:210 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T18   IOSTANDARD LVCMOS18  } [get_ports {ETH_TXD[1]}]
set_property src_info {type:XDC file:7 line:211 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17   IOSTANDARD LVCMOS18  } [get_ports {ETH_TXD[2]}]
set_property src_info {type:XDC file:7 line:212 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18   IOSTANDARD LVCMOS18  } [get_ports {ETH_TXD[3]}]
set_property src_info {type:XDC file:7 line:213 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16   IOSTANDARD LVCMOS18  } [get_ports {ETH_TXC}]
set_property src_info {type:XDC file:7 line:214 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14   IOSTANDARD LVCMOS18  } [get_ports {ETH_MDIO}]
set_property src_info {type:XDC file:7 line:215 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15   IOSTANDARD LVCMOS18  } [get_ports {ETH_INT_N}]
set_property src_info {type:XDC file:7 line:216 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13   IOSTANDARD LVCMOS18  } [get_ports {ETH_RST_N}]
set_property src_info {type:XDC file:7 line:217 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16   IOSTANDARD LVCMOS18  } [get_ports {ETH_RX_CTL}]
set_property src_info {type:XDC file:7 line:218 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16   IOSTANDARD LVCMOS18  } [get_ports {ETH_TX_CTL}]
set_property src_info {type:XDC file:7 line:226 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10   IOSTANDARD LVCMOS18  } [get_ports {FLASH_CLK_FPGA_CCLK}]
set_property src_info {type:XDC file:7 line:227 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L13   IOSTANDARD LVCMOS18  } [get_ports {FLASH_CS_N}]
set_property src_info {type:XDC file:7 line:228 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17   IOSTANDARD LVCMOS18  } [get_ports {FLASH_DI}]
set_property src_info {type:XDC file:7 line:229 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18   IOSTANDARD LVCMOS18  } [get_ports {FLASH_DO_FPGA_DIN}]
set_property src_info {type:XDC file:7 line:230 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN L14   IOSTANDARD LVCMOS18  } [get_ports {FLASH_WP_N}]
set_property src_info {type:XDC file:7 line:231 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14   IOSTANDARD LVCMOS18  } [get_ports {FLASH_HOLD_N}]
set_property src_info {type:XDC file:7 line:234 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15   IOSTANDARD LVCMOS18  } [get_ports {Rst_N}]
set_property src_info {type:XDC file:7 line:237 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12   IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ0_UARTRX}]
set_property src_info {type:XDC file:7 line:238 export:INPUT save:NONE read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12   IOSTANDARD LVCMOS18  } [get_ports {FX3_DQ2_UARTTX}]
