# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0.xci
# IP: The module: 'Mars_AX3_axi_timer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_timer_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0.xci
# IP: The module: 'Mars_AX3_axi_timer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
