# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# TCL: F:/GitHub/Mars_AX3_PM3_Reference_Design/src/Mars_AX3_PM3.tcl

# XDC: F:/GitHub/Mars_AX3_PM3_Reference_Design/src/Mars_AX3_LED_timing.xdc

# Block Designs: bd/Mars_AX3/Mars_AX3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3 || ORIG_REF_NAME==Mars_AX3} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_axi_timer_0 || ORIG_REF_NAME==Mars_AX3_axi_timer_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_xadc_wiz_0_0/Mars_AX3_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_xadc_wiz_0_0 || ORIG_REF_NAME==Mars_AX3_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_microblaze_xlconcat_0/Mars_AX3_microblaze_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_microblaze_xlconcat_0 || ORIG_REF_NAME==Mars_AX3_microblaze_xlconcat_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_IIC_0/Mars_AX3_IIC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_IIC_0 || ORIG_REF_NAME==Mars_AX3_IIC_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_LEDs_0/Mars_AX3_LEDs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_LEDs_0 || ORIG_REF_NAME==Mars_AX3_LEDs_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_QSPI_0/Mars_AX3_QSPI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_QSPI_0 || ORIG_REF_NAME==Mars_AX3_QSPI_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_UART_0/Mars_AX3_UART_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_UART_0 || ORIG_REF_NAME==Mars_AX3_UART_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_microblaze_CPU_0/Mars_AX3_microblaze_CPU_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_microblaze_CPU_0 || ORIG_REF_NAME==Mars_AX3_microblaze_CPU_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_xbar_0/Mars_AX3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_xbar_0 || ORIG_REF_NAME==Mars_AX3_xbar_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_interconnect_CPU_0/Mars_AX3_interconnect_CPU_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_interconnect_CPU_0 || ORIG_REF_NAME==Mars_AX3_interconnect_CPU_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_mdm_0_0 || ORIG_REF_NAME==Mars_AX3_mdm_0_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_microblaze_axi_intc_0/Mars_AX3_microblaze_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_microblaze_axi_intc_0 || ORIG_REF_NAME==Mars_AX3_microblaze_axi_intc_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_dlmb_v10_0/Mars_AX3_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_dlmb_v10_0 || ORIG_REF_NAME==Mars_AX3_dlmb_v10_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_ilmb_v10_0/Mars_AX3_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_ilmb_v10_0 || ORIG_REF_NAME==Mars_AX3_ilmb_v10_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_dlmb_bram_if_cntlr_0/Mars_AX3_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Mars_AX3_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_ilmb_bram_if_cntlr_0/Mars_AX3_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Mars_AX3_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_lmb_bram_0/Mars_AX3_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_lmb_bram_0 || ORIG_REF_NAME==Mars_AX3_lmb_bram_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_SDRAM_0 || ORIG_REF_NAME==Mars_AX3_SDRAM_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_xbar_1/Mars_AX3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_xbar_1 || ORIG_REF_NAME==Mars_AX3_xbar_1} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_interconnect_DDR_0/Mars_AX3_interconnect_DDR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_interconnect_DDR_0 || ORIG_REF_NAME==Mars_AX3_interconnect_DDR_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_0_0/Mars_AX3_rst_mig_7series_0_100M_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_rst_mig_7series_0_100M_0_0 || ORIG_REF_NAME==Mars_AX3_rst_mig_7series_0_100M_0_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_1_0/Mars_AX3_rst_mig_7series_0_100M_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_rst_mig_7series_0_100M_1_0 || ORIG_REF_NAME==Mars_AX3_rst_mig_7series_0_100M_1_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_axi_ethernet_0 || ORIG_REF_NAME==Mars_AX3_axi_ethernet_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_clk_wiz_0 || ORIG_REF_NAME==Mars_AX3_clk_wiz_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_axi_dma_0/Mars_AX3_axi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_axi_dma_0 || ORIG_REF_NAME==Mars_AX3_axi_dma_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_auto_pc_0/Mars_AX3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_auto_pc_0 || ORIG_REF_NAME==Mars_AX3_auto_pc_0} -quiet] -quiet

# IP: bd/Mars_AX3/ip/Mars_AX3_auto_cc_0/Mars_AX3_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mars_AX3_auto_cc_0 || ORIG_REF_NAME==Mars_AX3_auto_cc_0} -quiet] -quiet

# XDC: bd/Mars_AX3/Mars_AX3_ooc.xdc
