# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.runs/synth_1/Mars_AX3_PM3.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache C:/Users/Artak/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-36968-Artak-New/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.cache/wt [current_project]
set_property parent.project_path F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic DDR3_ADDR_WIDTH=14 [current_fileset]
set src_rc [catch { 
  puts "source F:/GitHub/Mars_AX3_PM3_Reference_Design/scripts/settings.tcl"
  source F:/GitHub/Mars_AX3_PM3_Reference_Design/scripts/settings.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script F:/GitHub/Mars_AX3_PM3_Reference_Design/scripts/settings.tcl failed"
  return -code error
}
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib F:/GitHub/Mars_AX3_PM3_Reference_Design/src/Mars_AX3_PM3.vhd
add_files F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/Mars_AX3.bd
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_timer_0/Mars_AX3_axi_timer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_xadc_wiz_0_0/Mars_AX3_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_xadc_wiz_0_0/Mars_AX3_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_IIC_0/Mars_AX3_IIC_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_IIC_0/Mars_AX3_IIC_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_LEDs_0/Mars_AX3_LEDs_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_LEDs_0/Mars_AX3_LEDs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_LEDs_0/Mars_AX3_LEDs_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_QSPI_0/Mars_AX3_QSPI_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_QSPI_0/Mars_AX3_QSPI_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_QSPI_0/Mars_AX3_QSPI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_QSPI_0/Mars_AX3_QSPI_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_UART_0/Mars_AX3_UART_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_UART_0/Mars_AX3_UART_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_UART_0/Mars_AX3_UART_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_CPU_0/Mars_AX3_microblaze_CPU_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_CPU_0/Mars_AX3_microblaze_CPU_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_CPU_0/Mars_AX3_microblaze_CPU_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_xbar_0/Mars_AX3_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_mdm_0_0/Mars_AX3_mdm_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_axi_intc_0/Mars_AX3_microblaze_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_axi_intc_0/Mars_AX3_microblaze_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_axi_intc_0/Mars_AX3_microblaze_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_dlmb_v10_0/Mars_AX3_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_ilmb_v10_0/Mars_AX3_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_dlmb_bram_if_cntlr_0/Mars_AX3_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_ilmb_bram_if_cntlr_0/Mars_AX3_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_lmb_bram_0/Mars_AX3_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0/user_design/constraints/Mars_AX3_SDRAM_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_SDRAM_0/Mars_AX3_SDRAM_0/user_design/constraints/Mars_AX3_SDRAM_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_xbar_1/Mars_AX3_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_0_0/Mars_AX3_rst_mig_7series_0_100M_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_0_0/Mars_AX3_rst_mig_7series_0_100M_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_0_0/Mars_AX3_rst_mig_7series_0_100M_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_1_0/Mars_AX3_rst_mig_7series_0_100M_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_1_0/Mars_AX3_rst_mig_7series_0_100M_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_rst_mig_7series_0_100M_1_0/Mars_AX3_rst_mig_7series_0_100M_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_0/bd_a7e0_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_0/synth/bd_a7e0_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_0/bd_a7e0_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_a7e0_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_a7e0_mac_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_a7e0_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_1/synth/bd_a7e0_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_2/bd_a7e0_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_3/bd_a7e0_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/bd_a7e0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/synth/Mars_AX3_axi_ethernet_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_clk_wiz_0/Mars_AX3_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_dma_0/Mars_AX3_axi_dma_0.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_dma_0/Mars_AX3_axi_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_dma_0/Mars_AX3_axi_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_auto_pc_0/Mars_AX3_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_auto_cc_0/Mars_AX3_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_auto_cc_0/Mars_AX3_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_auto_cc_0/Mars_AX3_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/Mars_AX3_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_microblaze_CPU_0/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -unmanaged F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/constrs_1/imports/src/Mars_AX3_PM3.tcl
set_property used_in_implementation false [get_files F:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/constrs_1/imports/src/Mars_AX3_PM3.tcl]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Mars_AX3_PM3 -part xc7a100tcsg324-2
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Mars_AX3_PM3.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Mars_AX3_PM3_utilization_synth.rpt -pb Mars_AX3_PM3_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
