# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0.xci
# IP: The module: 'Mars_AX3_axi_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/bd_a7e0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0 || ORIG_REF_NAME==bd_a7e0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_0/bd_a7e0_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_eth_buf_0 || ORIG_REF_NAME==bd_a7e0_eth_buf_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_1/bd_a7e0_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_mac_0 || ORIG_REF_NAME==bd_a7e0_mac_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_2/bd_a7e0_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_c_shift_ram_0_0 || ORIG_REF_NAME==bd_a7e0_c_shift_ram_0_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_3/bd_a7e0_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_c_counter_binary_0_0 || ORIG_REF_NAME==bd_a7e0_c_counter_binary_0_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_4/bd_a7e0_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_xlconstant_0_0 || ORIG_REF_NAME==bd_a7e0_xlconstant_0_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_5/bd_a7e0_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_util_vector_logic_0_0 || ORIG_REF_NAME==bd_a7e0_util_vector_logic_0_0} -quiet] -quiet

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/bd_a7e0_ooc.xdc

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_ethernet_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/synth/Mars_AX3_axi_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0.xci
# IP: The module: 'Mars_AX3_axi_ethernet_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/bd_a7e0.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0 || ORIG_REF_NAME==bd_a7e0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_0/bd_a7e0_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_eth_buf_0 || ORIG_REF_NAME==bd_a7e0_eth_buf_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_1/bd_a7e0_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_mac_0 || ORIG_REF_NAME==bd_a7e0_mac_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_2/bd_a7e0_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_c_shift_ram_0_0 || ORIG_REF_NAME==bd_a7e0_c_shift_ram_0_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_3/bd_a7e0_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_c_counter_binary_0_0 || ORIG_REF_NAME==bd_a7e0_c_counter_binary_0_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_4/bd_a7e0_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_xlconstant_0_0 || ORIG_REF_NAME==bd_a7e0_xlconstant_0_0} -quiet] -quiet

# IP: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/ip/ip_5/bd_a7e0_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a7e0_util_vector_logic_0_0 || ORIG_REF_NAME==bd_a7e0_util_vector_logic_0_0} -quiet] -quiet

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/bd_0/bd_a7e0_ooc.xdc

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/Mars_AX3_axi_ethernet_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/GitHub/Mars_AX3_PM3_Reference_Design/Vivado/MA-AX3-100-2I-D8/Mars_AX3_PM3.srcs/sources_1/bd/Mars_AX3/ip/Mars_AX3_axi_ethernet_0/synth/Mars_AX3_axi_ethernet_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mars_AX3_axi_ethernet_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
